/*
 * MicrovisionChain API Document
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.8
 * Contact: heqiming@mvcapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mvcapi.mvc.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddressBalance
 */
public class AddressBalanceTest {
    private final AddressBalance model = new AddressBalance();

    /**
     * Model tests for AddressBalance
     */
    @Test
    public void testAddressBalance() {
        // TODO: test AddressBalance
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'confirmed'
     */
    @Test
    public void confirmedTest() {
        // TODO: test confirmed
    }

    /**
     * Test the property 'unconfirmed'
     */
    @Test
    public void unconfirmedTest() {
        // TODO: test unconfirmed
    }

}
