/*
 * MicrovisionChain API Document
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.8
 * Contact: heqiming@mvcapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mvcapi.mvc.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OutputInfo
 */
public class OutputInfoTest {
    private final OutputInfo model = new OutputInfo();

    /**
     * Model tests for OutputInfo
     */
    @Test
    public void testOutputInfo() {
        // TODO: test OutputInfo
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'spent'
     */
    @Test
    public void spentTest() {
        // TODO: test spent
    }

    /**
     * Test the property 'spentTxid'
     */
    @Test
    public void spentTxidTest() {
        // TODO: test spentTxid
    }

    /**
     * Test the property 'spentIndex'
     */
    @Test
    public void spentIndexTest() {
        // TODO: test spentIndex
    }

    /**
     * Test the property 'spentHeight'
     */
    @Test
    public void spentHeightTest() {
        // TODO: test spentHeight
    }

}
