/*
 * MicrovisionChain API Document
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.8
 * Contact: heqiming@mvcapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mvcapi.mvc.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for XpubRequest
 */
public class XpubRequestTest {
    private final XpubRequest model = new XpubRequest();

    /**
     * Model tests for XpubRequest
     */
    @Test
    public void testXpubRequest() {
        // TODO: test XpubRequest
    }

    /**
     * Test the property 'xpub'
     */
    @Test
    public void xpubTest() {
        // TODO: test xpub
    }

    /**
     * Test the property 'skipHeight'
     */
    @Test
    public void skipHeightTest() {
        // TODO: test skipHeight
    }

    /**
     * Test the property 'initReceiveIndex'
     */
    @Test
    public void initReceiveIndexTest() {
        // TODO: test initReceiveIndex
    }

    /**
     * Test the property 'initChangeIndex'
     */
    @Test
    public void initChangeIndexTest() {
        // TODO: test initChangeIndex
    }

}
