/*
 * MicrovisionChain API Document
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mvcapi.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractFtGenesisCirculation
 */
public class ContractFtGenesisCirculationTest {
    private final ContractFtGenesisCirculation model = new ContractFtGenesisCirculation();

    /**
     * Model tests for ContractFtGenesisCirculation
     */
    @Test
    public void testContractFtGenesisCirculation() {
        // TODO: test ContractFtGenesisCirculation
    }

    /**
     * Test the property 'confirmed'
     */
    @Test
    public void confirmedTest() {
        // TODO: test confirmed
    }

    /**
     * Test the property 'unconfirmed'
     */
    @Test
    public void unconfirmedTest() {
        // TODO: test unconfirmed
    }

}
