/*
 * MicrovisionChain API Document
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mvcapi.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Get total circulation for specific genesis of ft token.
 */
@ApiModel(description = "Get total circulation for specific genesis of ft token.")
@JsonPropertyOrder({
  ContractFtGenesisCirculation.JSON_PROPERTY_CONFIRMED,
  ContractFtGenesisCirculation.JSON_PROPERTY_UNCONFIRMED
})
@JsonTypeName("ContractFtGenesisCirculation")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-10T16:23:17.579988+09:00[Asia/Tokyo]")
public class ContractFtGenesisCirculation {
  public static final String JSON_PROPERTY_CONFIRMED = "confirmed";
  private Long confirmed;

  public static final String JSON_PROPERTY_UNCONFIRMED = "unconfirmed";
  private Long unconfirmed;


  public ContractFtGenesisCirculation confirmed(Long confirmed) {
    
    this.confirmed = confirmed;
    return this;
  }

   /**
   * Confirmed circulation of the token(Sum of confirmed amount).
   * @return confirmed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Confirmed circulation of the token(Sum of confirmed amount).")
  @JsonProperty(JSON_PROPERTY_CONFIRMED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getConfirmed() {
    return confirmed;
  }


  public void setConfirmed(Long confirmed) {
    this.confirmed = confirmed;
  }


  public ContractFtGenesisCirculation unconfirmed(Long unconfirmed) {
    
    this.unconfirmed = unconfirmed;
    return this;
  }

   /**
   * Unconfirmed circulation of the token(Unconfirmed new token - Unconfirmed spent).
   * @return unconfirmed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unconfirmed circulation of the token(Unconfirmed new token - Unconfirmed spent).")
  @JsonProperty(JSON_PROPERTY_UNCONFIRMED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUnconfirmed() {
    return unconfirmed;
  }


  public void setUnconfirmed(Long unconfirmed) {
    this.unconfirmed = unconfirmed;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractFtGenesisCirculation contractFtGenesisCirculation = (ContractFtGenesisCirculation) o;
    return Objects.equals(this.confirmed, contractFtGenesisCirculation.confirmed) &&
        Objects.equals(this.unconfirmed, contractFtGenesisCirculation.unconfirmed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmed, unconfirmed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractFtGenesisCirculation {\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    unconfirmed: ").append(toIndentedString(unconfirmed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

